project:
  type: website
  output-dir: docs

website:
  title: "John McGrath"
  favicon: favicon-32x32.png
  navbar:
    title: false
    logo: logo_transparent.png
    right:
    - href: index.qmd
      text: Home
      icon: house
    - href: about.qmd
      text: About Me
      icon: person-fill
    - href: Projects/index.qmd
      text: My Projects
      icon: folder
    - href: JohnMcGrathCV1.pdf
      text: MY CV
      icon: file-earmark-text
      target: _blank
    - href: "mailto:john.mcgrath42@mail.dcu.ie"
      text: Email
      icon: envelope
  page-footer:
    background: light
    left: John McGrath, 2026


format:
  html:
    theme:
    - morph
    - styles.scss
    toc: true
    filters:
      - fontawesome



