project:
  type: website
  output-dir: docs

website:
  title: "John McGrath"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - href: documents/CV.pdf
        text: CV
        target: _blank

format:
  html:
    theme:
      - solana
      - brand
    css: styles.css
    toc: true



