---
title: "Reflection"
toc: false
---

## E-portfolio Reflection

The process of creating my E-portfolio has been a very interesting and rewarding experience. At the beginning of the module, I felt out of my depth because everything we were learning was unfamiliar to me. Seeing examples of previous students' e-portfolios made me wonder how I would ever get to the level displayed in those examples by using HTML, CSS, GitHub, and Quarto. 

Thankfully, week by week through the lectures, all these things started to make more sense, and things began to fall into place. The interactive nature of the classes was a big help. Every class, we got time to execute tasks that were important to building our e-portfolio, and we could ask Damien for help if we needed it, and then he would demonstrate to the class how to do it correctly. 

With the help of the lecture slides, I was able to start to build from the ground up and, taking inspiration from previous examples, I had the necessary knowledge to create my website as I had envisioned it.

Going forward, I hope to leverage not only the skills I learned from this process but also its outcome - my website, to showcase to employers my projects, skills, and experiences. I intend to keep this portfolio up to date and carry it with me throughout my professional career.
